### ISSUE TITLE
Linkable search results missing

### ISSUE THREAD

**Issue by drikkes** [microdotblog/plugin-tweetarchive#1]
Just a feature idea: Wouldn't it be awesome, if you could link to search queries in the tweet archive?

**Comment by manton** [comment]
I agree! It should be possible. I'll take a look at it.

**Comment by manton** [comment]
This has been finished. Now when you search it updates the URL and you can copy/paste the URL and it'll run the search next time the page is loaded. This is in version 1.0.3 of the plug-in.

**Comment by drikkes** [comment]
Great, it works. Thanks!
